name: Hprofile-Actions
on: workflow_dispatch
jobs:
 testing:
  runs-on: ubuntu-latest
  steps:
   - name: Code checkout
     uses: actions/checkout@v4
     
   - name: Maven test
     run: maven test

   - name: Checkstyle
     run: mvn checkstyle:checkstyle 
  
   - name: setup 
     uses: actions/setup-java@v3
     with: 
      distribution: 'temurin'
      java-version: '11'

    # Setup sonar-scanner for java 11
   - name: Setup SonarQube
     uses: warchant/setup-sonar-scanner@v7
    # Run sonar-scanner
   - name: SonarQube Scan
     run: sonar-scanner
        -Dsonar.host.url=${{ secrets.SONAR_URL }}
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        -Dsonar.sources=src/
        -Dsonar.junit.reportsPath=target/surefire-reports/
        -Dsonar.jacoco.reportsPath=target/jacoco.exec
        -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml
        -Dsonar.java.binaries=target/test-classes/com/visualpath/account1