name: Hprofile-Actions
on: workflow-dispatch
jobs:
 testing:
  runs-on: ubuntu-latest
  steps:
   - name: Code checkout
     uses: actions/checkout@v4
     
   - name: Maven test
     run: maven test

   - name: Checkstyle
     run: mvn checkstyle:checkstyle 
   
